# Generated by Django 5.2.6 on 2025-09-08 05:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('preview_photo', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Фото превью')),
                ('has_photoset', models.BooleanField(default=False, verbose_name='Фотосет')),
                ('show_on_main', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыть новость')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='sponsors/', verbose_name='Лого')),
            ],
            options={
                'verbose_name': 'Спонсор',
                'verbose_name_plural': 'Спонсоры',
            },
        ),
        migrations.CreateModel(
            name='StaffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип персонала',
                'verbose_name_plural': 'Типы персонала',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название команды')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Фото')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('staff_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stafftype', verbose_name='Тип персонала')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='MatchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('league', models.CharField(max_length=200, verbose_name='Лига')),
                ('venue', models.CharField(max_length=200, verbose_name='Место')),
                ('score_team_a', models.PositiveIntegerField(default=0, verbose_name='Счет Команда А')),
                ('score_team_b', models.PositiveIntegerField(default=0, verbose_name='Счет команда Б')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыть карточку')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_a', to='api.team', verbose_name='Команда А')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_b', to='api.team', verbose_name='Команда Б')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TournamentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('league', models.CharField(max_length=200, verbose_name='Лига')),
                ('venue', models.CharField(max_length=200, verbose_name='Место')),
                ('position', models.PositiveIntegerField(verbose_name='Место в турнирной таблице')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыть карточку')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['-date'],
            },
        ),
    ]
