# Generated by Django 5.2.6 on 2025-09-08 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_season_player_is_hidden_player_season'),
    ]

    operations = [
    ]
