# Generated by Django 5.2.6 on 2025-09-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_player_options_player_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchcard',
            name='team_a',
            field=models.CharField(max_length=200, verbose_name='Команда А'),
        ),
        migrations.AlterField(
            model_name='matchcard',
            name='team_b',
            field=models.CharField(max_length=200, verbose_name='Команда Б'),
        ),
        migrations.AlterField(
            model_name='tournamentcard',
            name='team',
            field=models.CharField(max_length=200, verbose_name='Команда'),
        ),
    ]
