# Generated by Django 5.2.6 on 2025-09-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_matchcard_team_a_alter_matchcard_team_b_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentcard',
            options={'ordering': ['-date_start'], 'verbose_name': 'Турнир', 'verbose_name_plural': 'Турниры'},
        ),
        migrations.RemoveField(
            model_name='tournamentcard',
            name='date',
        ),
        migrations.AddField(
            model_name='tournamentcard',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='tournamentcard',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
