# Generated by Django 5.2.6 on 2025-09-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_tournamentcard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentcard',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='tournamentcard',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
