# Generated by Django 5.2.6 on 2025-09-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='news_url',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на новость'),
        ),
    ]
