# Generated by Django 5.2.6 on 2025-09-09 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_event_news_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
        migrations.CreateModel(
            name='SchoolLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(verbose_name='Информация')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Местоположение школы',
                'verbose_name_plural': 'Местоположения школы',
            },
        ),
    ]
