# Generated by Django 5.2.6 on 2025-09-09 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_school_schoollocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollocation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_set', to='api.school', verbose_name='Школа'),
        ),
    ]
