# Generated by Django 5.2.6 on 2025-09-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_schoollocation_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
